"""Durable, provider-neutral coordination primitives."""

from .db import CoordinatorDB, coordinator_path
from .leases import (
    acquire_resource,
    admit_session,
    assert_resource_lease,
    heartbeat_session,
    release_admission,
    release_resource,
    recover_session,
    recovery_report,
    process_start_identity,
    renew_admission,
    renew_resource,
)
from .scopes import acquire_account_scope, acquire_change_scope, allocate_worktree
from .store import (
    CoordinatorConflictError,
    CoordinatorError,
    IllegalTransitionError,
    StaleVersionError,
    answer_question,
    append_event,
    cancel_session,
    complete_session,
    create_quant_session,
    create_session,
    events_since,
    get_session,
    record_attempt,
    record_question,
    resume_session,
    seed_quant_iteration_floor,
    session_status,
    transition_session,
    update_checkpoint,
)

__all__ = [
    "CoordinatorDB",
    "CoordinatorConflictError",
    "CoordinatorError",
    "IllegalTransitionError",
    "StaleVersionError",
    "answer_question",
    "append_event",
    "acquire_resource",
    "acquire_change_scope",
    "acquire_account_scope",
    "admit_session",
    "assert_resource_lease",
    "heartbeat_session",
    "allocate_worktree",
    "coordinator_path",
    "create_quant_session",
    "create_session",
    "cancel_session",
    "complete_session",
    "events_since",
    "get_session",
    "record_attempt",
    "record_question",
    "release_admission",
    "release_resource",
    "recover_session",
    "recovery_report",
    "process_start_identity",
    "renew_admission",
    "renew_resource",
    "resume_session",
    "seed_quant_iteration_floor",
    "session_status",
    "transition_session",
    "update_checkpoint",
]
